apiVersion: v1
kind: Pod
metadata:
  name: test-ed
  labels:
    app: redis
    tier: dev
spec:
  containers:
    - name: test-container
      image: redis
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir: {}
