apiVersion: v1
kind: Pod
metadata:
  name: test-cm
spec:
  containers:
    - name: test-container
      image: redis
      volumeMounts:
        - name: config
          mountPath: /redis-master
  volumes:
    - name: config
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: ./redis.conf
