apiVersion: v1
kind: Pod
metadata:
  name: test-secret
spec:
  containers:
    - name: test-container
      image: redis
      volumeMounts:
        - name: foo
          mountPath: /etc/foo
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: my-secret
