apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
  labels:
    app: monitor
spec:
  selector:
    matchExpressions:
      - { key: name, operator: In, values: [fluentd] }
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
        - name: fluentd
          image: gcr.io/google-containers/fluentd-elasticsearch:1.20
          ports:
            - containerPort: 80
